### ISSUE TITLE
下载后缺失.m文件

### ISSUE THREAD

**Issue by lrc201307** [wokenshin/KenshinPro#1]
请问下载运行后，发现缺失好几个.m文件

**Comment by wokenshin** [comment]
已经做了修改，如果还报错的话，可以暂时将报错部分注释掉。 谢谢回复

**Comment by huangxuhui7** [comment]
楼主你好，Classes/Controller/subNav下缺少很多文件

**Comment by wokenshin** [comment]
Hi sorry 现在才看到评论， 我赢重新更新项目了。你可以再试试 thanks
